name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_languages: yes
          # plugin_topics: yes
          # plugin_stars: yes
          # plugin_habits: yes
          # plugin_followup: yes
          # plugin_reactions: yes
          # plugin_people: yes
          # plugin_stargazers: yes
          # plugin_code: yes
          # plugin_code_lines: 30               # Only display snippets with less than 12 lines
          # plugin_code_load: 100               # Fetch 100 events from activity
          # plugin_code_visibility: public      # Only display snippets from public activity
          # plugin_activity: yes
          # plugin_achievements: yes
          # plugin_notable: yes
          # plugin_rss: yes
          # plugin_rss_source: https://jekyll.lwd-temp.top/feed.xml  # RSS feed
          # plugin_rss_limit: 6                                  # Limit to 6 items
          debug: yes
          verify: yes
